from ai.alerts.alarm_manager import AlarmManager


class AlertController:

    def __init__(self):
        self.alarm_manager = AlarmManager()

    def process(self, alert_data):
        """
        Process the output generated by AlertEngine.
        """

        alert_level = alert_data["alert_level"]

        if alert_level == "WARNING":
            self.alarm_manager.start_warning()

        elif alert_level == "CRITICAL":
            self.alarm_manager.start_critical()

        else:
            self.alarm_manager.stop()

        return {
            "alert_level": alert_level,
            "alarm_active": self.alarm_manager.is_active,
            "alarm_status": self.alarm_manager.current_level
        }

    def stop(self):
        """Stop all active alerts."""
        self.alarm_manager.stop()